### ISSUE TITLE
오타 발견

### ISSUE THREAD

**Issue by toneyparky** [WITH-SOPT-SERVER/SHARED-LEARNING#7]
https://github.com/WITH-SOPT-SERVER/SHARED-LEARNING/blob/master/Javascript.md#%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85-%EA%B8%B0%EB%B0%98-%EC%96%B8%EC%96%B4

프로토타입 기반 언어
프로토타입 기반 언어에서는 클래스라는 개념이 존재하지 않습니다. 대신 여러 """종휴"""의 Built-in 객체들이 시스템 상에 존재하게 됩니다.. 또한 객체 원형의 위임 과정을 통해 상속 과정이 구현됩니다,

종휴 -> 종류

**Comment by heesung6701** [comment]
수정하고 Pull Request로 만들어서 올려주세요!

**Comment by toneyparky** [comment]
got it
